version: '3.8'
services:
  web:
    build: .
    image: ${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA:-latest}
    labels:
      - caddy: "${DOMAINS}"
      - caddy.reverse_proxy: "{{ upstreams }}"
    ports:
      - "3000:3000"
    networks:
      - caddy 
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
networks:
  caddy:
    external: true
