version: '3.8'
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    labels:
      caddy: "${CADDY_PROXY_URL}"
      caddy.respond: / "Hello, Caddy 1" 200
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      restart_policy:
        condition: any

networks:
  caddy:
    external: true
volumes:
  caddy_data:
