version: '3.8'
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    labels:
      caddy: peteredm.com
      caddy.respond: / "Hello, Caddy" 200
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      restart_policy:
        condition: any

  web:
    build: .
    image: ghcr.io/peterje/swarm:latest
    labels:
      caddy: swarm.peteredm.com
      caddy.reverse_proxy: web:3000
    ports:
      - "3000:3000"
    networks:
      - caddy  # Changed to use the same network as Caddy
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  caddy:
    external: true
volumes:
  caddy_data:
