version: '3.8'

services:
  # We use Caddy as a reverse proxy to handle all network ingress.
  # That traffic can then be TLS terminated and proxied to the app.
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  web:
    labels:
      caddy: swarm.peteredm.com
      caddy.reverse_proxy: web:3000
    build: .
    image: ghcr.io/peterje/swarm:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  caddy:
    external: true

volumes:
  caddy_data:
