name: build and deploy preview
on:
  push:
    branches:
      - '**'
      - '!main'  # exclude main branch if you don't want to deploy it
permissions:
  contents: read
  packages: write
  pull-requests: write  # Add this permission to comment on PRs
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write  # Add this permission to the job as well
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch-name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # Replace invalid characters with hyphens and convert to lowercase
            BRANCH=$(echo "${GITHUB_HEAD_REF}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
            echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
            echo "original_branch=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          else
            BRANCH=$(echo "${GITHUB_REF#refs/heads/}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
            echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
            echo "original_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi
          
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
            type=raw,value=${{ steps.branch-name.outputs.branch }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create env file
        run: |
          touch .env.deploy
          echo "DOMAINS=preview-${{ steps.branch-name.outputs.branch }}.peteredm.com" >> .env.deploy

      - name: Deploy stack
        uses: cssnr/stack-deploy-action@v1
        with:
          name: app-${{ steps.branch-name.outputs.branch }}
          file: app.stack.yml
          host: peteredm.com
          user: peter
          ssh_key: ${{ secrets.SSH_KEY }}
          env_file: .env.deploy

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const url = `https://preview-${context.payload.pull_request.head.ref.toLowerCase().replace(/[^a-z0-9-]/g, '-')}.peteredm.com`;
            const comment = `🚀 Preview deployment is ready!\n\n[View Preview](${url})`;
            
            // Get existing comments
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            // Find if we already commented
            const botComment = comments.data.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Preview deployment is ready');
            });
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: comment
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }
